### ISSUE TITLE
Google answer #7329379 Only Provides GoogleDriveFSSetup.exe

### ISSUE THREAD

**Issue by MikuAuahDark** [phuze/windows-10-missing-search-icons#6]

**Comment by phuze** [comment]
Thank you. Looks like Google updated those pages. I've reflected that [change](https://github.com/phuze/windows-10-missing-search-icons/commit/12cafb61567d2ef2c9775d5ea185a4fe435608de). Previously, they offered two separate installers -- one for desktop users, and one for system administrators to deploy across their organization. Looks like they've consolidated these installers.

**Comment by MikuAuahDark** [comment]
Well the problem is I'm using that `GoogleDriveFSSetup.exe` and the problem arise.

Removing Drive FS would be a solution but I use it for work.
