### ISSUE TITLE
Another solution 

### ISSUE THREAD

**Issue by ahmed98Osama** [phuze/windows-10-missing-search-icons#7]
worked for me after trying all available solution on all well-known websites

then I tried 
update 1: Python Repair Tool
Update 2: Google Drive File Stream
although I don't have used this app before 

My Solution :

1: Enable Windows Administrator Account 

Select “Start” and type “CMD“.
Right-click “Command Prompt” then choose “Run as administrator“.
If prompted, enter a username and password that grants admin rights to the computer.
Type: net user administrator /active:yes.
Press “Enter

2: sign out then sign in to that user 

3: check if Search Icons working ex. calculator

4: open run WINDOWS + R 

5; put 

%LocalAppData%\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache

and hit ok

6: found folder with name 100 or 125 or 150 etc then  take a copy and paste it in C:\

7: log out this login in your normal user 

8:take a copy from  C:\ 

9: open run WINDOWS + R 

10; put 

%LocalAppData%\Packages\Microsoft.Windows.Search_cw5n1h2txyewy\LocalState\AppIconCache

and hit ok

11: paste it  accept overwrite

12: it should work now 

13: Select “Start” and type “CMD“.
Right-click “Command Prompt” then choose “Run as administrator“.
If prompted, enter a username and password that grants admin rights to the computer.
Type: net user administrator /active:no
Press “Enter“.
Replace “yes” with “no” to disable the admin account on the welcome screen.

**Comment by joeljose1001** [comment]
This works. Thanks. 
Also, if you have any PWA apps installed via edge, those icons shall not be restored since those apps don't exist in the admin account. 
Users may either reinstall the said PWAs or use the manual method mentioned in the main post. The former is recommended for normal users who do not like to mess with permissions.
Update: Reinstalling those apps does not fix the issue. Something is fundamentally broken in windows.

**Comment by ahmed98Osama** [comment]
https://superuser.com/questions/1319157/some-windows-10-uwp-icons-not-displaying-on-search-or-in-settings/1441161#1441161:~:text=all%20the%20problem%20got%20resolved.%20So%2C%20today%20in%20this%20answer%20I%20will%20show%20you%20how%20you%20can%20fix%20the%20broken%20UWP%20icon%20on%20Windows%20Search%20issue%20while%20keeping%20GDFS%20installed. 

a very good solution
