### ISSUE TITLE
This tool is unable to fix my UWP apps.

### ISSUE THREAD

**Issue by Delta18-Git** [phuze/windows-10-missing-search-icons#8]
I use a custom DPI scale of 130 as all other scales look weird on my laptop. However, when I deleted the contents of the folder, the icons got replaced by a black outline of a pictorial representation of a window. 
I copied and pasted the files of another user which partially fixed it, but all UWP apps didn't have a proper icon and have an icon of the photos app. 
The tool given here doesn't help as none of the corrupted files are discovered by it. I tried manually editing the files from the StoreIcon.png files, but no luck. 
I now am running the command to re-register all UWP apps, but it has not worked. I have no clue what to do next. I had once installed DriveFS, but was never able to set it up and had uninstalled it, however I am using the new Google Drive App.

**Comment by Delta18-Git** [comment]
Normal Start Menu:
![image](https://user-images.githubusercontent.com/64347927/126902099-7716a896-bc5f-4b28-85c1-40c606951630.png)

Search Menu:
![image](https://user-images.githubusercontent.com/64347927/126902109-8ea1eb33-4607-4a6e-8b2c-70b65cc2e4a6.png)

**Comment by Squall-Leonhart** [comment]
the new google drive is google drive fs.
